title: CO ČÍST?
baseURL: https://406665.github.io/Web-o-knihach-pro-deti/
languageCode: cs-cz
publishDir: docs
googleAnalytics: UA-117879209-1

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Description of my new site.
  authors: Authors

